In [1]:
import pandas as pd
import twinlab as tl

df = pd.DataFrame({'X': [1, 2, 3, 4], 'y': [1, 4, 9, 16]})
dataset = tl.Dataset("my_dataset")
dataset.upload(df)
emulator = tl.Emulator('emulator')
emulator.train(dataset, ['X'], ['y'])

          ====== TwinLab Client Initialisation ======
          Version     : 2.4.0
          Server      : https://x1wx0cskd1.execute-api.eu-west-2.amazonaws.com/dev
          Environment : /Users/sergiochavez/twinlab-demos/.env

In [2]:
tl.list_emulators()

['0',
 '1',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '2',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '3',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '4',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '5',
 '6',
 '7',
 '8',
 '9',
 'Batman4_model',
 'Batman4_model',
 'Batman4_model',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'SimpleGP',
 'emulator',
 'example_emulator',
 'example_emulator0',
 'test_model']

In [15]:
import os
import pandas as pd
dataframe = pd.read_csv('multi_fidelity.csv')
dataset = tl.Dataset(id="multi_fidelity")
dataset.upload(dataframe)

# Create and train emulator
estimator_params = tl.EstimatorParams(estimator_type="multi_fidelity_gp")
params = tl.TrainParams(
        train_test_ratio=0.8,
        estimator_params=estimator_params,
        seed=123,
        fidelity="fidelity",
    )
emulator = tl.Emulator(id="multi_fidelity")
emulator.train(dataset, inputs=["x","z"], outputs=["y"], params=params)

    # Test view
view = emulator.view()
del view["modal_handle"]  # Remove modal handle because it changes every time

    # Test summarise
summary = emulator.summarise()

In [16]:
emulator.view()

{'model_id': 'multi_fidelity',
 'fidelity': 'fidelity',
 'estimator': 'gaussian_process_regression',
 'estimator_kwargs': {'detrend': False, 'estimator_type': 'multi_fidelity_gp'},
 'decompose_inputs': False,
 'decompose_outputs': False,
 'input_explained_variance': None,
 'input_retained_dimensions': None,
 'output_explained_variance': None,
 'output_retained_dimensions': None,
 'train_test_ratio': 0.8,
 'model_selection': False,
 'model_selection_kwargs': {'seed': None,
  'evaluation_metric': 'MSLL',
  'val_ratio': 0.2,
  'base_kernels': 'restricted',
  'depth': 1,
  'beam': None},
 'seed': 123,
 'inputs': ['x', 'z'],
 'outputs': ['y'],
 'dataset_id': 'multi_fidelity',
 'modal_handle': 'fc-3O2UotaSEVJgAYDU32p2WU'}

In [17]:
emulator.summarise()

{'transformer_diagnostics': [],
 'estimator_diagnostics': {'covar_module': 'ScaleKernel(\n  (base_kernel): ProductKernel(\n    (kernels): ModuleList(\n      (0): LinearTruncatedFidelityKernel(\n        (raw_power_constraint): Positive()\n        (power_prior): GammaPrior()\n        (covar_module_unbiased): MaternKernel(\n          (lengthscale_prior): GammaPrior()\n          (raw_lengthscale_constraint): Positive()\n        )\n        (covar_module_biased): MaternKernel(\n          (lengthscale_prior): GammaPrior()\n          (raw_lengthscale_constraint): Positive()\n        )\n      )\n    )\n  )\n  (outputscale_prior): GammaPrior()\n  (raw_outputscale_constraint): Positive()\n)',
  'mean_module': 'ConstantMean()',
  'likelihood.noise_covar.raw_noise': [0.0048984],
  'likelihood.noise_covar.noise_prior.concentration': 1.100000023841858,
  'likelihood.noise_covar.noise_prior.rate': 0.05000000074505806,
  'likelihood.noise_covar.raw_noise_constraint.lower_bound': 9.999999747378752e-05,
  'likelihood.noise_covar.raw_noise_constraint.upper_bound': 'array(inf)',
  'mean_module.raw_constant': 0.39298792758715756,
  'covar_module.raw_outputscale': 4.138400454337178,
  'covar_module.base_kernel.kernels.0.raw_power': [-0.05893547],
  'covar_module.base_kernel.kernels.0.raw_power_constraint.lower_bound': 0.0,
  'covar_module.base_kernel.kernels.0.raw_power_constraint.upper_bound': 'array(inf)',
  'covar_module.base_kernel.kernels.0.power_prior.concentration': 3.0,
  'covar_module.base_kernel.kernels.0.power_prior.rate': 3.0,
  'covar_module.base_kernel.kernels.0.covar_module_unbiased.raw_lengthscale': 'array([[-1.21449881, -0.46471764]])',
  'covar_module.base_kernel.kernels.0.covar_module_unbiased.lengthscale_prior.concentration': 3.0,
  'covar_module.base_kernel.kernels.0.covar_module_unbiased.lengthscale_prior.rate': 6.0,
  'covar_module.base_kernel.kernels.0.covar_module_unbiased.raw_lengthscale_constraint.lower_bound': 0.0,
  'covar_module.base_kernel.kernels.0.covar_module_unbiased.raw_lengthscale_constraint.upper_bound': 'array(inf)',
  'covar_module.base_kernel.kernels.0.covar_module_biased.raw_lengthscale': 'array([[1.58768   , 2.41769519]])',
  'covar_module.base_kernel.kernels.0.covar_module_biased.lengthscale_prior.concentration': 6.0,
  'covar_module.base_kernel.kernels.0.covar_module_biased.lengthscale_prior.rate': 2.0,
  'covar_module.base_kernel.kernels.0.covar_module_biased.raw_lengthscale_constraint.lower_bound': 0.0,
  'covar_module.base_kernel.kernels.0.covar_module_biased.raw_lengthscale_constraint.upper_bound': 'array(inf)',
  'covar_module.outputscale_prior.concentration': 2.0,
  'covar_module.outputscale_prior.rate': 0.15000000596046448,
  'covar_module.raw_outputscale_constraint.lower_bound': 0.0,
  'covar_module.raw_outputscale_constraint.upper_bound': 'array(inf)',
  'outcome_transform.means': [[2.95997136]],
  'outcome_transform.stdvs': [[4.3728079]],
  'outcome_transform._stdvs_sq': [[19.12144894]],
  'outcome_transform._is_trained': True,
  'input_transform._coefficient': 'array([[9.68317953e-01, 5.64400000e+02, 5.00000000e-01]])',
  'input_transform._offset': 'array([[0.01027151, 2.        , 0.5       ]])',
  'likelihood.noise_covar.original_noise': [0.0048984],
  'mean_module.original_constant': 0.39298792758715756,
  'covar_module.original_outputscale': 4.154222956938124,
  'covar_module.base_kernel.kernels.0.original_power': [0.66411355],
  'covar_module.base_kernel.kernels.0.covar_module_unbiased.original_lengthscale': 'array([[0.259945 , 0.4875442]])',
  'covar_module.base_kernel.kernels.0.covar_module_biased.original_lengthscale': 'array([[1.77366091, 2.50307147]])'}}

In [30]:
import os
import pandas as pd
dataframe = pd.read_csv('multi_fidelity.csv') #This dataframe is already in dev resources
dataset = tl.Dataset(id="multi_fidelity")
dataset.upload(dataframe)

# Create and train emulator
estimator_params = tl.EstimatorParams(estimator_type="multi_fidelity_gp")
params = tl.TrainParams(
        train_test_ratio=0.8,
        estimator_params=estimator_params,
        seed=123,
        #fidelity="fidelity",
    )
emulator = tl.Emulator(id="multi_fidelity")
emulator.train(dataset, inputs=["x","z"], outputs=["y","z"], params=params)

    # Test view
view = emulator.view()
del view["modal_handle"]  # Remove modal handle because it changes every time

    # Test summarise
summary = emulator.summarise()

In [31]:
emulator.view()

{'model_id': 'multi_fidelity',
 'fidelity': None,
 'estimator': 'gaussian_process_regression',
 'estimator_kwargs': {'detrend': False, 'estimator_type': 'multi_fidelity_gp'},
 'decompose_inputs': False,
 'decompose_outputs': False,
 'input_explained_variance': None,
 'input_retained_dimensions': None,
 'output_explained_variance': None,
 'output_retained_dimensions': None,
 'train_test_ratio': 0.8,
 'model_selection': False,
 'model_selection_kwargs': {'seed': None,
  'evaluation_metric': 'MSLL',
  'val_ratio': 0.2,
  'base_kernels': 'restricted',
  'depth': 1,
  'beam': None},
 'seed': 123,
 'inputs': ['x', 'z'],
 'outputs': ['y', 'z'],
 'dataset_id': 'multi_fidelity',
 'modal_handle': 'fc-21GFOGmNUKLr2aLs3Pi3wZ'}

In [19]:
# Sample data
data = {
    ('Group1', 'Subgroup1'): [10, 20, 30],
    ('Group1', 'Subgroup2'): [40, 50, 60],
    ('Group2', 'Subgroup1'): [70, 80, 90],
    ('Group2', 'Subgroup2'): [100, 110, 120]
}

# Create DataFrame with MultiIndex in columns
df = pd.DataFrame(data)

print(df)
print(df)

     Group1              Group2
  Subgroup1 Subgroup2 Subgroup1 Subgroup2
0        10        40        70       100
1        20        50        80       110
2        30        60        90       120
     Group1              Group2
  Subgroup1 Subgroup2 Subgroup1 Subgroup2
0        10        40        70       100
1        20        50        80       110
2        30        60        90       120

In [21]:
test_data=emulator.view_test_data()

In [23]:
result=emulator.predict(test_data)

In [26]:
type(result)

tuple

In [34]:
sample1=emulator.sample(test_data,num_samples=2)
sample2=emulator.sample(test_data,num_samples=2)

In [36]:
sample1

          y                    z
          0         1          0          1
0  4.725518  1.327792  48.494606  43.206232
1  0.369628 -0.288327   6.516642   7.006419
2  6.325411  6.866203   3.301738   1.615816
3  1.448961 -0.029312   5.377535   5.613816

In [37]:
sample2

          y                    z
          0         1          0          1
0  0.875821  3.817539  42.542734  46.962452
1  0.450354  0.635990   6.758069   6.502314
2  3.976380  8.492023   2.642545   1.223864
3  0.012715  0.813152   5.144163   4.863581

In [39]:
data1 = {
        ("y", "0"): [-2.749357, 0.959321, 0.566999, -0.154889],
        ("y", "1"): [-0.462247, -0.230350, 2.881398, 2.786605],
        ("x", "0"): [0.959321, 0.566999, -0.154889, -0.462247],
        ("x", "1"): [-0.230350, 2.881398, 2.786605, -2.749357],
    }

df1 = pd.DataFrame(data1)

In [40]:

data2 = {
        ("y", "0"): [1.0, 2.0, 3.0, 4.0],
        ("y", "1"): [5.0, 6.0, 7.0, 8.0],
        ("x", "0"): [9.0, 10.0, 11.0, 12.0],
        ("x", "1"): [13.0, 14.0, 15.0, 16.0],
    }

df2 = pd.DataFrame(data2)

In [41]:
tl.join_samples(df1,df2)

          x                               y
          0         1     2     3         0         1    2    3
0  0.959321 -0.230350   9.0  13.0 -2.749357 -0.462247  1.0  5.0
1  0.566999  2.881398  10.0  14.0  0.959321 -0.230350  2.0  6.0
2 -0.154889  2.786605  11.0  15.0  0.566999  2.881398  3.0  7.0
3 -0.462247 -2.749357  12.0  16.0 -0.154889  2.786605  4.0  8.0

In [43]:
type(tl.list_datasets())

list

In [35]:
tl.join_samples(sample1,sample2)

          y                                        z                        \
          0         1         2         3          0          1          2
0  4.725518  1.327792  0.875821  3.817539  48.494606  43.206232  42.542734
1  0.369628 -0.288327  0.450354  0.635990   6.516642   7.006419   6.758069
2  6.325411  6.866203  3.976380  8.492023   3.301738   1.615816   2.642545
3  1.448961 -0.029312  0.012715  0.813152   5.377535   5.613816   5.144163


           3
0  46.962452
1   6.502314
2   1.223864
3   4.863581

In [44]:
tl.list_datasets()

['0.1subset',
 '01subset',
 'AdamNewDataset',
 'Batman',
 'Batman2',
 'Batman4',
 'Batman5',
 'Batman6',
 'My%20data',
 'Quadratic',
 'Testing_Data',
 'Tritium_Desorption_Data',
 'apicall_test',
 'basic',
 'example',
 'example_data',
 'example_std',
 'fidelity_df',
 'functional_data',
 'fusion_dataset',
 'gardening',
 'jc_dataset',
 'my_dataset',
 'new_Data',
 'new_data2',
 'new_points',
 'prueba',
 'prueba2',
 'prueba3',
 'queuing_dataset',
 'sergio_datasetx',
 'sergio_df',
 'std_df',
 'test-data',
 'test-data2',
 'test-data22',
 'test_dataset']

In [45]:
tl.list_emulators()

['0',
 '1',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '2',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '3',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '4',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '5',
 '6',
 '7',
 '8',
 '9',
 'Batman4_model',
 'Batman4_model',
 'Batman4_model',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'Sergio_emulator',
 'SimpleGP',
 'emulator',
 'example_emulator',
 'example_emulator0',
 'test_model']

In [47]:
tl.core.list_example_datasets()

['biscuits', 'gardening', 'quickstart', 'tritium-desorption']

In [48]:
tl.list_example_datasets()

['biscuits', 'gardening', 'quickstart', 'tritium-desorption']

# TWIN 621

In [49]:
import twinlab as tl

dataset = tl.Dataset(id="does-not-exist")
emulator = tl.Emulator(id="new-campaign")
emulator.train(dataset=dataset, inputs=["X"], outputs=["y"])

Non-success status code

Exception: Error Code: 400 - {'message': 'Unable to load data from your account: sergio/models/new-campaign/processes/b8b33676-fb98-4795-9920-d1a51c8aa50a/b8b33676-fb98-4795-9920-d1a51c8aa50a.json'}

In [1]:
import twinlab as tl
import pandas as pd

          ====== TwinLab Client Initialisation ======
          Version     : 2.4.0
          Server      : http://127.0.0.1:3000
          Environment : /Users/sergiochavez/twinlab-demos/.env

In [5]:
dataset = tl.Dataset(id="does-not-exist")
df = pd.DataFrame({'X': [1, 2, 3, 4], 'y': [1, 4, 9, 16]})
dataset.upload(df)
emulator = tl.Emulator(id="new-campaign")
emulator.train(dataset=dataset, inputs=["X"], outputs=["y"])

In [5]:
emulator.summarise()

{'transformer_diagnostics': [],
 'estimator_diagnostics': {'covar_module': 'ScaleKernel(\n  (base_kernel): MaternKernel(\n    (lengthscale_prior): GammaPrior()\n    (raw_lengthscale_constraint): Positive()\n  )\n  (outputscale_prior): GammaPrior()\n  (raw_outputscale_constraint): Positive()\n)',
  'mean_module': 'ConstantMean()',
  'likelihood.noise_covar.raw_noise': [0.02783039],
  'likelihood.noise_covar.noise_prior.concentration': 1.100000023841858,
  'likelihood.noise_covar.noise_prior.rate': 0.05000000074505806,
  'likelihood.noise_covar.raw_noise_constraint.lower_bound': 9.999999747378752e-05,
  'likelihood.noise_covar.raw_noise_constraint.upper_bound': 'array(inf)',
  'mean_module.raw_constant': 0.14731902077686065,
  'covar_module.raw_outputscale': 1.4066929659870258,
  'covar_module.base_kernel.raw_lengthscale': [[-0.27411343]],
  'covar_module.base_kernel.lengthscale_prior.concentration': 3.0,
  'covar_module.base_kernel.lengthscale_prior.rate': 6.0,
  'covar_module.base_kernel.raw_lengthscale_constraint.lower_bound': 0.0,
  'covar_module.base_kernel.raw_lengthscale_constraint.upper_bound': 'array(inf)',
  'covar_module.outputscale_prior.concentration': 2.0,
  'covar_module.outputscale_prior.rate': 0.15000000596046448,
  'covar_module.raw_outputscale_constraint.lower_bound': 0.0,
  'covar_module.raw_outputscale_constraint.upper_bound': 'array(inf)',
  'outcome_transform.means': [[7.5]],
  'outcome_transform.stdvs': [[6.55743852]],
  'outcome_transform._stdvs_sq': [[43.0]],
  'outcome_transform._is_trained': True,
  'input_transform._coefficient': [[3.0]],
  'input_transform._offset': [[1.0]],
  'likelihood.noise_covar.original_noise': [0.02783039],
  'mean_module.original_constant': 0.14731902077686065,
  'covar_module.original_outputscale': 1.6257899488162522,
  'covar_module.base_kernel.original_lengthscale': [[0.56545348]]}}

In [8]:
emulator.view_test_data()

Empty DataFrame
Columns: [X, y]
Index: []

In [4]:
dataset = tl.Dataset(id="does-not-exist2")
emulator = tl.Emulator(id="new-campaign")
emulator.train(dataset=dataset, inputs=["X"], outputs=["y"])

Non-success status code

Exception: Error Code: 400 - {'message': 'The dataset you are trying to train on does not exist on your twinLab cloud account. Please ensure you have uploaded your dataset.'}

In [9]:
emulator = tl.Emulator(id="biscuits")

In [11]:
emulator.summarise()

{'transformer_diagnostics': [],
 'estimator_diagnostics': {'covar_module': 'ScaleKernel(\n  (base_kernel): MaternKernel(\n    (lengthscale_prior): GammaPrior()\n    (raw_lengthscale_constraint): Positive()\n  )\n  (outputscale_prior): GammaPrior()\n  (raw_outputscale_constraint): Positive()\n)',
  'mean_module': 'ConstantMean()',
  'likelihood.noise_covar.raw_noise': 'array([[0.10164052],\n       [0.0154432 ]])',
  'likelihood.noise_covar.noise_prior.concentration': 1.100000023841858,
  'likelihood.noise_covar.noise_prior.rate': 0.05000000074505806,
  'likelihood.noise_covar.raw_noise_constraint.lower_bound': 9.999999747378752e-05,
  'likelihood.noise_covar.raw_noise_constraint.upper_bound': 'array(inf)',
  'mean_module.raw_constant': 'array([-0.32023739, -0.35267355])',
  'covar_module.raw_outputscale': 'array([0.90634717, 1.73870673])',
  'covar_module.base_kernel.raw_lengthscale': 'array([[[-1.03162221, -0.43846782]],\n\n       [[-0.71675942, -0.47237553]]])',
  'covar_module.base_kernel.lengthscale_prior.concentration': 3.0,
  'covar_module.base_kernel.lengthscale_prior.rate': 6.0,
  'covar_module.base_kernel.raw_lengthscale_constraint.lower_bound': 0.0,
  'covar_module.base_kernel.raw_lengthscale_constraint.upper_bound': 'array(inf)',
  'covar_module.outputscale_prior.concentration': 2.0,
  'covar_module.outputscale_prior.rate': 0.15000000596046448,
  'covar_module.raw_outputscale_constraint.lower_bound': 0.0,
  'covar_module.raw_outputscale_constraint.upper_bound': 'array(inf)',
  'outcome_transform.means': 'array([[ 2684.44444444, 15731.9       ]])',
  'outcome_transform.stdvs': 'array([[ 186.59656422, 2397.94864103]])',
  'outcome_transform._stdvs_sq': 'array([[  34818.27777778, 5750157.685     ]])',
  'outcome_transform._is_trained': True,
  'input_transform._coefficient': 'array([[0.5, 4. ]])',
  'input_transform._offset': 'array([[ 1.8, 16. ]])',
  'likelihood.noise_covar.original_noise': 'array([[0.10164052],\n       [0.0154432 ]])',
  'mean_module.original_constant': 'array([-0.32023739, -0.35267355])',
  'covar_module.original_outputscale': 'array([1.24567053, 1.90061088])',
  'covar_module.base_kernel.original_lengthscale': 'array([[[0.30485499, 0.49775495]],\n\n       [[0.39765615, 0.48459621]]])'}}

In [13]:
emulator.view_train_data()

,Pack price [GBP],Number of biscuits per pack,Number of packs sold,Profit [GBP]
0,2.30,20.0,2385.0,16695.0
1,2.25,20.0,2553.0,16594.5
2,2.00,18.0,2812.0,15747.2
3,1.80,16.0,2647.0,13764.4
4,1.90,16.0,2755.0,17081.0
5,1.95,16.0,2642.0,17701.4
6,2.20,18.0,2516.0,19121.6
7,2.00,20.0,2886.0,11544.0
8,2.05,20.0,2964.0,13338.0

# Experiment